base_url = "https://tripleter.github.io"
title = "Tripletter"
description = "Exploring Graph Algorithms, Knowledge Graphs, and AI Applications"
compile_sass = true
build_search_index = true
generate_feed = true

[markdown]
highlight_code = true
