name: Deploy site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build and deploy
        uses: shalzz/zola-deploy-action@v0.17.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          build_dir: public
          deploy_branch: gh-pages
          clean: true
          keep_files: true
