name: Deploy site

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install Zola
        run: |
          curl -sSf https://get.zola.rs | bash
          export PATH="$HOME/.local/bin:$PATH"

      - name: Build site
        run: zola build
